
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy

  export const environment = {
    production: false,
    FIREBASE_API_KEY: 'AIzaSyAZedN_hMussPs1W25mNzoSgU8B8lQ5hsk'
  };
