export class Hotel {
    hotelId: string
    hotelName: string
    address: Address
    facilities: number[]
    adminId: string
    autoGenerated: boolean

    constructor(docId: string, data: any) {
        this.hotelId = docId
        this.hotelName = data.hotelName
        this.address = data.address
        this.facilities = data.facilities
        this.adminId = data.adminId
        this.autoGenerated = data.autoGenerated
    }
}

class Address {
    street: string
    city: string
    state: string
    zip: string

    constructor() { }
}