export class Hotel {
    hotelId: string
    hotelName: string
    address: Address
    facilities: number[]
    adminId: string
    autoGenerated: boolean
    imgUrlList: string[]

    constructor(docId: string, data: HotelData) {
        this.hotelId = docId
        this.hotelName = data.hotelName
        this.address = data.address
        this.facilities = data.facilities
        this.adminId = data.adminId
        this.autoGenerated = data.autoGenerated
        this.imgUrlList = data.imgUrlList
    }
}

export class HotelData {
    hotelName: string
    address: Address
    facilities: number[]
    adminId: string
    autoGenerated: boolean
    imgUrlList: string[]
}

export class Address {
    street: string
    city: string
    state: string
    zip: string

    constructor() { }
}
